
eureka:
  instance:
    hostname: eureka-naming-server
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-naming-server:8080/eureka/

spring:
  application:
    name: eureka-naming-server

server:
  port: 8080

