spring:
  config:
    import: notification.yml, thymeleaf.yml
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: user_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: R2-D2-F1-L1

server:
  port: 89

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: TaskManager

