spring:
  application:
    name: task-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: task_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://task-db:5432/task-service
    username: root
    password: root

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-naming-service:8080/eureka/
  instance:
    hostname: eureka-naming-service
    preferIpAddress: true

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: TaskManager


